"""Initial schema

Revision ID: 79a77033015d
Revises: 
Create Date: 2026-04-17 18:08:31.057101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a77033015d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('buywander_logins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bw_email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('encrypted_cookies', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buywander_login_user', 'buywander_logins', ['user_id'], unique=False)
    op.create_table('notification_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_queue_created_at'), 'notification_queue', ['created_at'], unique=False)
    op.create_index('ix_notification_queue_retry', 'notification_queue', ['next_retry_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_token_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('user_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('login_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('auction_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['buywander_logins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_created_at'), 'event_log', ['created_at'], unique=False)
    op.create_index('ix_event_log_login', 'event_log', ['login_id'], unique=False)
    op.create_index('ix_event_log_user', 'event_log', ['user_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('login_id', sa.String(length=36), nullable=False),
    sa.Column('auction_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('my_bid', sa.Float(), nullable=False),
    sa.Column('store_location_id', sa.String(length=36), nullable=True),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['buywander_logins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_history_login', 'history', ['login_id'], unique=False)
    op.create_table('snipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('login_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('auction_uuid', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('snipe_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('winner_handle', sa.String(length=100), nullable=True),
    sa.Column('winner_id', sa.String(length=64), nullable=True),
    sa.Column('bid_count', sa.Integer(), nullable=True),
    sa.Column('my_max_bid', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('bid_placed', sa.Boolean(), nullable=True),
    sa.Column('is_me', sa.Boolean(), nullable=True),
    sa.Column('error_msg', sa.String(length=512), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['buywander_logins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snipe_login', 'snipes', ['login_id'], unique=False)
    op.create_index('ix_snipe_status', 'snipes', ['status'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('login_id', sa.String(length=36), nullable=True),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['buywander_logins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlist_user', 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlist_user', table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index('ix_snipe_status', table_name='snipes')
    op.drop_index('ix_snipe_login', table_name='snipes')
    op.drop_table('snipes')
    op.drop_index('ix_history_login', table_name='history')
    op.drop_table('history')
    op.drop_index('ix_event_log_user', table_name='event_log')
    op.drop_index('ix_event_log_login', table_name='event_log')
    op.drop_index(op.f('ix_event_log_created_at'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('user_config')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_notification_queue_retry', table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_created_at'), table_name='notification_queue')
    op.drop_table('notification_queue')
    op.drop_index('ix_buywander_login_user', table_name='buywander_logins')
    op.drop_table('buywander_logins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
