name: Cleanup Old Images
on:
  schedule:
    - cron: '0 0 * * SUN' # Runs weekly
  workflow_dispatch: # Allows manual trigger

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete dev and SHA images
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: ${{ github.repository_owner }}
          name: your-image-name
          token: ${{ secrets.GITHUB_TOKEN }}
          # Use a regex or specific tags to delete
          tag: "/^dev-.*|sha-.*/" 
